### ISSUE TITLE
Please re-evaluate projects. 2 weeks out of date isn't very helpful for the better projects.

### ISSUE THREAD

**Issue by Jaribeau** [PubInv/covid19-vent-list#42]
First off - thanks a million for this work. There are piles of projects out there, making it very difficult to find the projects that are heading in a solid direction, and have made good headway. I'm working with a team in Cambodia to setup production of ventilators, and despite the plethora of projects, it is very difficult to sift through the ones that are worth following and pursuing.

That said - given that this list has become so popular, it is *very* important that it stays at least reasonably up to date. If people miss-directed away from higher quality projects, and towards lower quality projects, it actively harms the global efforts. 

Since things are changing SO quickly, having projects that haven't been re-evaluated in 2 weeks makes those entries in the chart stale. In its current state, I cannot rely on this list to be a useful gage of where projects are at - which incredibly important for implementation teams like us on the ground.

I know this is a ton of work to do, and I SO much appreciate the time and energy you are putting into this, as well as the testing rig. Keep up the good work - it's a critical piece to the global effort!

P.S. I've been tracking the MIT E-Vent project closely. They have yet to release code or say when they intend to, which is frustrating, but their team, requirements, process, and documentation show a very solid understanding of the problem and what makes a good solution. I expect they will have something very good fully published soon.

**Comment by RobertLRead** [comment]
Thank you. Enrique and I are probably not going to re-evaluate things on a regular basis; there are many projects which seem not very active, and trying to figure out if they have changed in a way that requires reevaluation is not trivial. However, we are willing to be responsive. If someone claims a project has made progress and should be re-evaluated (especially if they summarize that progress), we will attempt to respond to immediately.

As I'm sure you suspect, this is a lot of work, and my main work is [VentMon](https://github.com/PubInv/ventmon-ventilator-inline-test-monitor). 

Yes, the MIT project has so far given the world nothing useful, and the same is true of the OxVent from Oxford. I fear that they make they have "the" solution instead of part of the solution. However, I am happy (and proud of my alma mater) to say that Rice University HAS open-sourced the Apollo BVM about 6 hours ago and it is fully open and clearly (though a bit oddly) documented and reproducible.
