### ISSUE TITLE
An Iranian ventilator (couldn't find repo link at first glance)

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/covid19-vent-list#92]
https://spectrum.ieee.org/the-institute/ieee-member-news/engineers-iran-open-source-ventilator?utm_source=techalert&utm_medium=email&utm_campaign=techalert-04-16-20&mkt_tok=eyJpIjoiTm1WaU1XVTROVFJoWlRNeSIsInQiOiJPRmpObVdieDVSMVcyeTlicnBJRXlqNjVUR1wvcGtjWEdoQit2S25neGVkVVpOeXl2WTJmazc0Yzh3KytPTkRMVGdyem11WGZXUDlTTDhOcjNlMEV0VDhUVmlpOHdrNndSUjl4ZSt6cWF1S1pLK3JmUVFBa0F0VjNyVm4wSTRZRDIifQ%3D%3D

**Comment by avinashbaskaran** [comment]
Dr. Read, 

It seems this isn't open as of yet. 

"We are aiming to make the design open source and will let other IEEE regions know. Since building this machine involves a combination of electrical, mechanical, and bioengineering, it is important to have members from all these field work together to build it."
